version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # if run docker on local, comment /etc/ssl:/etc/ssl
      - /etc/ssl:/etc/ssl
    depends_on:
      - node
    ports:
      - 80:80
      # if run docker on local, comment 443:443
      - 443:443
  node:
    build: .
  redis-server:
    image: redis:alpine
    ports:
      - 6379:6379
    expose: 
      - 6379
