version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - node
    ports:
      - 80:80
  node:
    build: .
  redis-server:
    image: redis:alpine
    ports:
      - 6379:6379
    expose: 
      - 6379
